import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../core/theme/app_colors.dart';
import '../../core/theme/app_text_styles.dart';
import '../../providers/category_provider.dart';
import '../../providers/debate_provider.dart';
import '../../providers/auth_provider.dart';
import '../../models/debate.dart';
import '../../widgets/common/verz_button.dart';
import '../../widgets/common/verz_text_field.dart';

class CreateDebateScreen extends ConsumerStatefulWidget {
  const CreateDebateScreen({super.key});

  @override
  ConsumerState<CreateDebateScreen> createState() => _CreateDebateScreenState();
}

class _CreateDebateScreenState extends ConsumerState<CreateDebateScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  String? _selectedCategoryId;

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  void _createDebate() async {
    if (_formKey.currentState!.validate() && _selectedCategoryId != null) {
      final authState = ref.read(authProvider);
      if (authState.user == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Please login to create a debate')),
        );
        return;
      }

      final newDebate = Debate(
        id: '', // Will be generated by Appwrite
        title: _titleController.text.trim(),
        description: _descriptionController.text.trim(),
        categoryId: _selectedCategoryId!,
        creatorId: authState.user!.id,
        mediaType: 'text',
        status: 'active',
        createdAt: DateTime.now(),
      );

      await ref.read(debateProvider.notifier).createDebate(newDebate);

      if (mounted) {
        final debateState = ref.read(debateProvider);
        if (debateState.error != null) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Error: ${debateState.error}'),
              backgroundColor: AppColors.error,
            ),
          );
        } else {
          context.pop();
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Debate created successfully!')),
          );
        }
      }
    } else if (_selectedCategoryId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select a category'), backgroundColor: AppColors.error),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final categoryState = ref.watch(categoryProvider);
    final debateState = ref.watch(debateProvider);
    final isLoading = debateState.isLoading;

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.close_rounded, color: Colors.white),
          onPressed: () => context.pop(),
        ),
        title: Text('START A DEBATE', style: AppTextStyles.labelMedium.copyWith(letterSpacing: 2)),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 20),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildSectionLabel('THE TOPIC'),
              const SizedBox(height: 16),
              VerzTextField(
                label: '',
                hintText: 'Should AI have constitutional rights?',
                controller: _titleController,
                validator: (v) => v == null || v.isEmpty ? 'Topic title is required' : null,
              ),
              const SizedBox(height: 32),
              _buildSectionLabel('DESCRIPTION & STAKES (OPTIONAL)'),
              const SizedBox(height: 16),
              VerzTextField(
                label: '',
                hintText: 'Explain why this debate matters now...',
                controller: _descriptionController,
                maxLines: 5,
              ),
              const SizedBox(height: 32),
              _buildSectionLabel('CATEGORY'),
              const SizedBox(height: 16),
              _buildCategorySelector(categoryState, isLoading),
              const SizedBox(height: 60),
              VerzButton(
                text: 'PUBLISH TO VERSZ',
                isLoading: isLoading,
                onPressed: isLoading ? null : _createDebate,
              ),
              const SizedBox(height: 40),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSectionLabel(String label) {
    return Text(
      label, 
      style: AppTextStyles.labelSmall.copyWith(color: AppColors.accent, fontWeight: FontWeight.w900, letterSpacing: 1.2),
    );
  }

  Widget _buildCategorySelector(CategoryState state, bool isLoading) {
    if (state.isLoading) {
      return const Center(child: CircularProgressIndicator(color: AppColors.primary));
    }

    return SizedBox(
      height: 46,
      child: ListView.separated(
        scrollDirection: Axis.horizontal,
        itemCount: state.categories.length,
        separatorBuilder: (_, __) => const SizedBox(width: 8),
        itemBuilder: (context, index) {
          final cat = state.categories[index];
          final isSelected = _selectedCategoryId == cat.id;
          return GestureDetector(
            onTap: isLoading ? null : () => setState(() => _selectedCategoryId = isSelected ? null : cat.id),
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              alignment: Alignment.center,
              decoration: BoxDecoration(
                color: isSelected ? AppColors.primary : AppColors.surface,
                borderRadius: BorderRadius.circular(23),
                border: Border.all(color: isSelected ? AppColors.primary : AppColors.surfaceLight),
              ),
              child: Text(
                '${cat.emoji} ${cat.name.toUpperCase()}',
                style: AppTextStyles.labelSmall.copyWith(
                  color: isSelected ? Colors.black : Colors.white,
                  fontWeight: FontWeight.w900,
                  fontSize: 10,
                ),
              ),
            ),
          );
        },
      ),
    );
  }
}
